### PR TITLE
fix: Add option to subscribe immediately to an observable.

### LINKED ISSUE #106: Why is subscribe() not in constructor() ? Moving it there solved a bug I had
I spent a few hours trying to understand a hard-to-debug problem in `rxToStream` where the source observable was completing before emitting values.

I ended up solving it by moving `this._subscription = this._source.subscribe(...)` in `constructor()`.

I'd rather not fork this lib though.

Why is the subscription made in the first `_read()` instead of `constructor()` ?

### PR DESCRIPTION
**Pull request by Jason3S**
fix #106

### CODE REVIEW

File: src/rxToStream.ts [hunk 1]
```diff
@@ -101,4 +89,40 @@ class ReadableObservableStream<T> extends stream.Readable {
             }
         }
     }
+
+    private subscribe() {
+        if (this._subscription) return;
```
Comment (Jason3S) [inline src/rxToStream.ts:94]: @vibl

The check is in the subscribe.

Comment (vibl) [reply src/rxToStream.ts:94]: Oops, sorry :-)

Comment (Jason3S) [reply src/rxToStream.ts:94]: I put it here to avoid double subscription.

The `if` could also be in the `_read()` function for a tiny-tiny bit more speed, but I thought it was better to have the
subscription logic in one place.

Comment (vibl) [reply src/rxToStream.ts:94]: Ok, although that makes the name of the method somewhat misleading (which is why I didn't think of looking into it).
